version: '3.8'
services:
  mil:
    build:
      context: ./mil
      dockerfile: Dockerfile
    ports:
      - "41888:41888"
      - "41887:41887"
    volumes:
      - /home/smk762/.mil:/home/komodian/.mil
    shm_size: '2gb'
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  kmd:
    build:
      context: ./kmd
      dockerfile: Dockerfile
    ports:
      - "7770:7770"
      - "7771:7771"
    volumes:
      - /home/smk762/.komodo_3p:/home/komodian/.komodo
      - /home/smk762/.zcash-params:/home/komodian/.zcash-params
    shm_size: '2gb'
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  mcl:
    build:
      context: ./mcl
      dockerfile: Dockerfile
    ports:
      - "33824:33824"
      - "33825:33825"
    volumes:
      - /home/smk762/.komodo_3p/MCL:/home/komodian/.komodo/MCL
      - /home/smk762/.zcash-params:/home/komodian/.zcash-params
    shm_size: '2gb'
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  vrsc:
    build:
      context: ./vrsc
      dockerfile: Dockerfile
    ports:
      - "30023:30023"
      - "30024:30024"
    volumes:
      - /home/smk762/.komodo_3p/VRSC:/home/komodian/.komodo/VRSC
      - /home/smk762/.zcash-params:/home/komodian/.zcash-params
    shm_size: '2gb'
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  tokel:
    build:
      context: ./tokel
      dockerfile: Dockerfile
    ports:
      - "30023:30023"
      - "30024:30024"
    volumes:
      - /home/smk762/.komodo_3p/TOKEL:/home/komodian/.komodo/TOKEL
      - /home/smk762/.zcash-params:/home/komodian/.zcash-params
    shm_size: '2gb'
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  chips:
    build:
      context: ./chips
      dockerfile: Dockerfile
    ports:
      - "30023:30023"
      - "30024:30024"
    volumes:
      - /home/smk762/.chips:/home/komodian/.chips
      - /home/smk762/.zcash-params:/home/komodian/.zcash-params
    shm_size: '2gb'
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  emc2:
    build:
      context: ./emc2
      dockerfile: Dockerfile
    ports:
      - "30023:30023"
      - "30024:30024"
    volumes:
      - /home/smk762/.einsteinium:/home/komodian/.einsteinium
    shm_size: '2gb'
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  aya:
    build:
      context: ./aya
      dockerfile: Dockerfile
    ports:
      - "30023:30023"
      - "30024:30024"
    volumes:
      - /home/smk762/.aryacoin:/home/komodian/.aryacoin
    shm_size: '2gb'
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
