version: '3.8'

x-zcash-params-volume:
  &zcash-params
  type: bind
  source: /home/smk762/.zcash-params
  target: /home/komodian/.zcash-params

services:
  aya:
    env_file:
      - .env
    environment:
      - COMMIT_HASH=94e6bc0
    build:
      context: ./aya
      dockerfile: Dockerfile
    ports:
      - "26001:26001"
      - "9333:9332"
    volumes:
      - /home/smk762/.aryacoin:/home/komodian/.aryacoin
    shm_size: '2gb'
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  chips:
    env_file:
      - .env
    environment:
      - COMMIT_HASH=6e7560a
    build:
      context: ./chips
      dockerfile: Dockerfile
    ports:
      - "57777:57777"
      - "57776:57776"
    volumes:
      - /home/smk762/.chips:/home/komodian/.chips
      - <<: *zcash-params
    shm_size: '2gb'
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  emc2:
    env_file:
      - .env
    environment:
      - COMMIT_HASH=c329ae6
    build:
      context: ./emc2
      dockerfile: Dockerfile
    ports:
      - "41878:41878"
      - "41879:41879"
    volumes:
      - /home/smk762/.einsteinium:/home/komodian/.einsteinium
    shm_size: '2gb'
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  kmd:
    env_file:
      - .env
    environment:
      - COMMIT_HASH=master
    build:
      context: ./kmd
      dockerfile: Dockerfile
    ports:
      - "7770:7770"
      - "7771:7771"
    volumes:
      - /home/smk762/.komodo_3p:/home/komodian/.komodo
      - <<: *zcash-params
    shm_size: '2gb'
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  mcl:
    env_file:
      - .env
    environment:
      - COMMIT_HASH=a92d834
    build:
      context: ./mcl
      dockerfile: Dockerfile
    ports:
      - "33824:33824"
      - "33825:33825"
    volumes:
      - /home/smk762/.komodo_3p/MCL:/home/komodian/.komodo/MCL
      - <<: *zcash-params
    shm_size: '2gb'
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  mil:
    env_file:
      - .env
    environment:
      - COMMIT_HASH=578bed7
    build:
      context: ./mil
      dockerfile: Dockerfile
    ports:
      - "41888:41888"
      - "41889:41889"
    volumes:
      - /home/smk762/.mil:/home/komodian/.mil
    shm_size: '2gb'
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  tokel:
    env_file:
      - .env
    environment:
      - COMMIT_HASH=d2e98de
    build:
      context: ./tokel
      dockerfile: Dockerfile
    ports:
      - "29404:29404"
      - "29405:29405"
    volumes:
      - /home/smk762/.komodo_3p/TOKEL:/home/komodian/.komodo/TOKEL
      - <<: *zcash-params
    shm_size: '2gb'
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  vrsc:
    env_file:
      - .env
    environment:
      - COMMIT_HASH=3f0f435
    build:
      context: ./vrsc
      dockerfile: Dockerfile
    ports:
      - "27485:27485"
      - "27486:27486"
    volumes:
      - /home/smk762/.komodo_3p/VRSC:/home/komodian/.komodo/VRSC
      - <<: *zcash-params
    shm_size: '2gb'
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"